/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { utils, Contract, ContractFactory, } from "ethers";
const _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "domain_hash_1155",
                type: "bytes32",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
];
const _bytecode = "0x6080604052348015600f57600080fd5b506040516080380380608083398181016040526020811015602f57600080fd5b5051600055603f8060416000396000f3fe6080604052600080fdfea2646970667358221220063f87e2343ff946c2d6b04d43f5f1a37ea1880917297aba5a44c95596dce24364736f6c63430007040033";
const isSuperArgs = (xs) => xs.length > 1;
export class LibEIP712__factory extends ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(domain_hash_1155, overrides) {
        return super.deploy(domain_hash_1155, overrides || {});
    }
    getDeployTransaction(domain_hash_1155, overrides) {
        return super.getDeployTransaction(domain_hash_1155, overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new Contract(address, _abi, signerOrProvider);
    }
}
LibEIP712__factory.bytecode = _bytecode;
LibEIP712__factory.abi = _abi;
