/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class ERC1155Mock extends Contract {
  functions: {
    balanceOf(_address: string, _id: number | string): Promise<BigNumber>;

    supportsInterface(_interfaceID: string): Promise<boolean>;

    writeValueInBin(
      _binValue: number | string,
      _index: number | string,
      _amount: number | string
    ): Promise<BigNumber>;

    getIDBinIndex(
      _id: number | string
    ): Promise<{
      bin: BigNumber;
      index: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    isApprovedForAll(_owner: string, _operator: string): Promise<boolean>;

    getValueInBin(
      _binValue: number | string,
      _index: number | string
    ): Promise<BigNumber>;

    safeBatchTransferFrom(
      _from: string,
      _to: string,
      _ids: (number | string)[],
      _amounts: (number | string)[],
      _data: (string)[]
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      _operator: string,
      _approved: boolean
    ): Promise<ContractTransaction>;

    safeTransferFrom(
      _from: string,
      _to: string,
      _id: number | string,
      _amount: number | string,
      _data: (string)[]
    ): Promise<ContractTransaction>;

    mockMint(
      _address: string,
      _type: number | string,
      _value: number | string
    ): Promise<ContractTransaction>;
  };
  filters: {
    Transfer(
      operator: null,
      from: null,
      to: null,
      ids: null,
      amounts: null
    ): EventFilter;

    ApprovalForAll(
      _owner: string | null,
      _operator: string | null,
      _approved: null
    ): EventFilter;

    Transfer(from: null, to: null, tokenType: null, amount: null): EventFilter;

    URI(_id: number | string | null, _value: null): EventFilter;

    Name(_id: number | string | null, _value: null): EventFilter;
  };
}
