/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class ERC1155Metadata extends Contract {
  functions: {
    uri(_id: number | string | BigNumber): Promise<string>;
  };
  filters: {
    URI(_uri: null, _id: number | string | BigNumber | null): EventFilter;
  };
}
