/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class ERC1155OperatorMock extends Contract {
  functions: {
    safeTransferFrom(
      _tokenAddress: string,
      _from: string,
      _to: string,
      _id: number | string | BigNumber,
      _value: number | string | BigNumber,
      _data: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    safeBatchTransferFrom(
      _tokenAddress: string,
      _from: string,
      _to: string,
      _ids: (number | string | BigNumber)[],
      _values: (number | string | BigNumber)[],
      _data: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
