/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class ERC1155TokenReceiver extends Contract {
  functions: {
    onERC1155Received(
      _operator: string,
      _from: string,
      _id: number | string,
      _value: number | string,
      _data: (string)[]
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      _operator: string,
      _from: string,
      _ids: (number | string)[],
      _values: (number | string)[],
      _data: (string)[]
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
