/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class ERC1271WalletMock extends Contract {
  functions: {
    isValidSignature(_hash: string, _signature: (string)[]): Promise<string>;

    setShouldReject(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    ERC1271_MAGIC_VAL(): Promise<string>;
    shouldReject(): Promise<boolean>;
    ERC1271_INVALID(): Promise<string>;
  };
  filters: {};
}
