/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ERC1155ReceiverMockInterface extends Interface {
  functions: {
    lastData: TypedFunctionDescription<{ encode([]: []): string }>;

    lastId: TypedFunctionDescription<{ encode([]: []): string }>;

    lastOperator: TypedFunctionDescription<{ encode([]: []): string }>;

    lastValue: TypedFunctionDescription<{ encode([]: []): string }>;

    shouldReject: TypedFunctionDescription<{ encode([]: []): string }>;

    setShouldReject: TypedFunctionDescription<{
      encode([_value]: [boolean]): string;
    }>;

    onERC1155Received: TypedFunctionDescription<{
      encode([_operator, _from, _id, _value, _data]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        Arrayish
      ]): string;
    }>;

    onERC1155BatchReceived: TypedFunctionDescription<{
      encode([_operator, _from, _ids, _values, _data]: [
        string,
        string,
        (BigNumberish)[],
        (BigNumberish)[],
        Arrayish
      ]): string;
    }>;

    supportsInterface: TypedFunctionDescription<{
      encode([interfaceID]: [Arrayish]): string;
    }>;
  };

  events: {
    TransferBatchReceiver: TypedEventDescription<{
      encodeTopics([_from, _to, _fromBalances, _toBalances]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    TransferSingleReceiver: TypedEventDescription<{
      encodeTopics([_from, _to, _fromBalance, _toBalance]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class ERC1155ReceiverMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ERC1155ReceiverMock;
  attach(addressOrName: string): ERC1155ReceiverMock;
  deployed(): Promise<ERC1155ReceiverMock>;

  on(event: EventFilter | string, listener: Listener): ERC1155ReceiverMock;
  once(event: EventFilter | string, listener: Listener): ERC1155ReceiverMock;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ERC1155ReceiverMock;
  removeAllListeners(eventName: EventFilter | string): ERC1155ReceiverMock;
  removeListener(eventName: any, listener: Listener): ERC1155ReceiverMock;

  interface: ERC1155ReceiverMockInterface;

  functions: {
    lastData(): Promise<string>;

    lastId(): Promise<BigNumber>;

    lastOperator(): Promise<string>;

    lastValue(): Promise<BigNumber>;

    shouldReject(): Promise<boolean>;

    setShouldReject(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _value: BigNumberish,
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    onERC1155BatchReceived(
      _operator: string,
      _from: string,
      _ids: (BigNumberish)[],
      _values: (BigNumberish)[],
      _data: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    supportsInterface(interfaceID: Arrayish): Promise<boolean>;
  };

  lastData(): Promise<string>;

  lastId(): Promise<BigNumber>;

  lastOperator(): Promise<string>;

  lastValue(): Promise<BigNumber>;

  shouldReject(): Promise<boolean>;

  setShouldReject(
    _value: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  onERC1155Received(
    _operator: string,
    _from: string,
    _id: BigNumberish,
    _value: BigNumberish,
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  onERC1155BatchReceived(
    _operator: string,
    _from: string,
    _ids: (BigNumberish)[],
    _values: (BigNumberish)[],
    _data: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  supportsInterface(interfaceID: Arrayish): Promise<boolean>;

  filters: {
    TransferBatchReceiver(
      _from: null,
      _to: null,
      _fromBalances: null,
      _toBalances: null
    ): EventFilter;

    TransferSingleReceiver(
      _from: null,
      _to: null,
      _fromBalance: null,
      _toBalance: null
    ): EventFilter;
  };

  estimate: {
    lastData(): Promise<BigNumber>;

    lastId(): Promise<BigNumber>;

    lastOperator(): Promise<BigNumber>;

    lastValue(): Promise<BigNumber>;

    shouldReject(): Promise<BigNumber>;

    setShouldReject(_value: boolean): Promise<BigNumber>;

    onERC1155Received(
      _operator: string,
      _from: string,
      _id: BigNumberish,
      _value: BigNumberish,
      _data: Arrayish
    ): Promise<BigNumber>;

    onERC1155BatchReceived(
      _operator: string,
      _from: string,
      _ids: (BigNumberish)[],
      _values: (BigNumberish)[],
      _data: Arrayish
    ): Promise<BigNumber>;

    supportsInterface(interfaceID: Arrayish): Promise<BigNumber>;
  };
}
