/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ERC1155MetadataMockInterface extends Interface {
  functions: {
    setBaseMetadataURI: TypedFunctionDescription<{
      encode([_newBaseMetadataURI]: [string]): string;
    }>;

    logURIsMock: TypedFunctionDescription<{
      encode([_tokenIDs]: [(BigNumberish)[]]): string;
    }>;

    logURIsMock2: TypedFunctionDescription<{
      encode([_tokenIDs, _URIs]: [(BigNumberish)[], (string)[]]): string;
    }>;
  };

  events: {
    URI: TypedEventDescription<{
      encodeTopics([_uri, _id]: [null, BigNumberish | null]): string[];
    }>;
  };
}

export class ERC1155MetadataMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ERC1155MetadataMock;
  attach(addressOrName: string): ERC1155MetadataMock;
  deployed(): Promise<ERC1155MetadataMock>;

  on(event: EventFilter | string, listener: Listener): ERC1155MetadataMock;
  once(event: EventFilter | string, listener: Listener): ERC1155MetadataMock;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ERC1155MetadataMock;
  removeAllListeners(eventName: EventFilter | string): ERC1155MetadataMock;
  removeListener(eventName: any, listener: Listener): ERC1155MetadataMock;

  interface: ERC1155MetadataMockInterface;

  functions: {
    uri(_id: BigNumberish): Promise<string>;

    setBaseMetadataURI(
      _newBaseMetadataURI: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    logURIsMock(
      _tokenIDs: (BigNumberish)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    logURIsMock2(
      _tokenIDs: (BigNumberish)[],
      _URIs: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  filters: {
    URI(_uri: null, _id: BigNumberish | null): EventFilter;
  };

  estimate: {
    setBaseMetadataURI(_newBaseMetadataURI: string): Promise<BigNumber>;

    logURIsMock(_tokenIDs: (BigNumberish)[]): Promise<BigNumber>;

    logURIsMock2(
      _tokenIDs: (BigNumberish)[],
      _URIs: (string)[]
    ): Promise<BigNumber>;
  };
}
