/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class ERC20Mock extends Contract {
  functions: {
    balanceOf(owner: string): Promise<BigNumber>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(
      spender: string,
      value: number | string
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      value: number | string
    ): Promise<ContractTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: number | string
    ): Promise<ContractTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: number | string
    ): Promise<ContractTransaction>;

    transfer(to: string, value: number | string): Promise<ContractTransaction>;

    mockMint(
      _address: string,
      _amount: number | string
    ): Promise<ContractTransaction>;

    batchTransfer(
      _tokens: (string)[],
      to: string,
      _amounts: (number | string)[]
    ): Promise<ContractTransaction>;

    totalSupply(): Promise<BigNumber>;
  };
  filters: {
    Transfer(from: string | null, to: string | null, value: null): EventFilter;

    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;
  };
}
