/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class ERC721 extends Contract {
  functions: {
    supportsInterface(interfaceId: string): Promise<boolean>;

    balanceOf(owner: string): Promise<BigNumber>;

    ownerOf(tokenId: number | string | BigNumber): Promise<string>;

    getApproved(tokenId: number | string | BigNumber): Promise<string>;

    isApprovedForAll(owner: string, operator: string): Promise<boolean>;

    approve(
      to: string,
      tokenId: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      to: string,
      approved: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    safeTransferFrom(
      from: string,
      to: string,
      tokenId: number | string | BigNumber,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {
    Transfer(
      from: string | null,
      to: string | null,
      tokenId: number | string | BigNumber | null
    ): EventFilter;

    Approval(
      owner: string | null,
      approved: string | null,
      tokenId: number | string | BigNumber | null
    ): EventFilter;

    ApprovalForAll(
      owner: string | null,
      operator: string | null,
      approved: null
    ): EventFilter;
  };
}
