/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IERC1155Metadata } from "./IERC1155Metadata";

export class IERC1155MetadataFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155Metadata {
    return new Contract(address, _abi, signerOrProvider) as IERC1155Metadata;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256"
      }
    ],
    name: "uri",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
