/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class IERC721Receiver extends Contract {
  functions: {
    onERC721Received(
      operator: string,
      from: string,
      tokenId: number | string,
      data: (string)[]
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
