/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class IERC1155Meta extends Contract {
  functions: {
    metaSafeTransferFrom(
      _from: string,
      _to: string,
      _id: number | string | BigNumber,
      _amount: number | string | BigNumber,
      _isGasFee: boolean,
      _data: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    metaSafeBatchTransferFrom(
      _from: string,
      _to: string,
      _ids: (number | string | BigNumber)[],
      _amounts: (number | string | BigNumber)[],
      _isGasFee: boolean,
      _data: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    metaSetApprovalForAll(
      _owner: string,
      _operator: string,
      _approved: boolean,
      _isGasFee: boolean,
      _data: (string)[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };
  filters: {};
}
