/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface LibEIP712Interface extends Interface {
  functions: {};

  events: {};
}

export class LibEIP712 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): LibEIP712;
  attach(addressOrName: string): LibEIP712;
  deployed(): Promise<LibEIP712>;

  on(event: EventFilter | string, listener: Listener): LibEIP712;
  once(event: EventFilter | string, listener: Listener): LibEIP712;
  addListener(eventName: EventFilter | string, listener: Listener): LibEIP712;
  removeAllListeners(eventName: EventFilter | string): LibEIP712;
  removeListener(eventName: any, listener: Listener): LibEIP712;

  interface: LibEIP712Interface;

  functions: {};

  filters: {};

  estimate: {};
}
