/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";

export class Migrations extends Contract {
  functions: {
    setCompleted(completed: number | string): Promise<ContractTransaction>;

    upgrade(new_address: string): Promise<ContractTransaction>;

    last_completed_migration(): Promise<BigNumber>;
    owner(): Promise<string>;
  };
  filters: {};
}
