/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter } from "ethers";
import { Provider } from "ethers/providers";
import { BigNumber } from "ethers/utils";
import { TransactionOverrides } from ".";

export class SignatureValidator extends Contract {
  functions: {
    isValidSignature(
      _signerAddress: string,
      _data: (string)[],
      _sig: (string)[]
    ): Promise<boolean>;
  };
  filters: {};
}
