/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20__factory } from "./ERC20__factory";
export { ERC20Mock__factory } from "./ERC20Mock__factory";
