on: [push]

name: ci

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/cache@master
        id: pnpm-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}
      - run: pnpm install
        if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}

  lint-ts:
    name: Typescript lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/cache@master
        id: pnpm-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}
      - run: pnpm lint:ts

  lint-sol:
    name: Solidity lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/cache@master
        id: pnpm-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}
      - run: pnpm lint:sol

  test:
    name: Test contracts
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/cache@master
        id: pnpm-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}
      - run: pnpm test

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   needs: [install]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 18
  #     - uses: actions/cache@master
  #       id: pnpm-cache
  #       with:
  #         path: |
  #           node_modules
  #           */*/node_modules
  #         key: ${{ runner.os }}-lerna-${{ hashFiles('**/package.json', '**/pnpm-lock.yaml') }}
  #     - run: pnpm coverage || true
  #     - name: Coveralls
  #       uses: coverallsapp/github-action@master
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
